name: GrapplingHook
author: SnowGears
description: A simple grappling hook plugin.
version: 1.6.5
api-version: 1.14
main: com.snowgears.grapplinghook.GrapplingHook
permissions:
    grapplinghook.pull.self:
        description: Allows player to pull themselves to a location
        default: op
    grapplinghook.pull.mobs:
        description: Allows player to pull mobs with the hook
        default: op
    grapplinghook.pull.players:
        description: Allows player to pull players with the hook
        default: op
    grapplinghook.pull.items:
        description: Allows player to pull items with the hook
        default: op
    grapplinghook.craft.<id>:
        description: Allows player to craft the grappling hook defined by the id in recipes.yml
        default: op
    grapplinghook.operator:
        description: Allows player to use commands for plugin
        default: op
    grapplinghook.player.nopull:
        description: Player can not be pulled by other players
        default: op
    grapplinghook.player.nocooldown:
        description: Player ignores grapple cooldown
        default: op
